module.exports = {
  NUMBER_OF_SIGNUPS: '# of signups',
  NUMBER_OF_UNIQUE_VISITORS: '# of unique affiliated visitors',
  NUMBER_OF_UNIQUE_UNAFFILIATED_VISITORS: '# of unique unaffiliated visitors',
  UNAFFILIATED_CONVERSION_RATE_OVERALL: 'unaffiliated conversion rate overall',
  NUMBER_OF_SIGNUPS_SCHOLARSHIP_TAB: '# of signups on scholarship tab',
  NUMBER_OF_UNIQUE_AFFILIATED_VISITORS_SCHOLARSHIP_TAB: '# of unique affiliated visitors on scholarship tab',
  NUMBER_OF_UNIQUE_UNAFFILIATED_VISITORS_SCHOLARSHIP_TAB: '# of unique unaffiliated visitors on scholarship tab',
  CONVERSION_RATE_SCHOLARSHIP_TAB: 'conversion rate on scholarship tab',
  NUMBER_OF_SIGNUPS_COMMUNITY_TAB: '# of signups on community tab',
  NUMBER_OF_UNIQUE_AFFILIATED_VISITORS_COMMUNITY_TAB: '# of unique affiliated visitors on community tab',
  NUMBER_OF_UNIQUE_UNAFFILIATED_VISITORS_COMMUNITY_TAB: '# of unique unaffiliated visitors on community tab',
  CONVERSION_RATE_COMMUNITY_TAB: 'conversion rate on community tab',
  NUMBER_OF_SIGNUPS_ACTION_TAB: '# of signups on action tab',
  NUMBER_OF_UNIQUE_AFFILIATED_VISITORS_ACTION_TAB: '# of unique affiliated visitors on action tab',
  NUMBER_OF_UNIQUE_UNAFFILIATED_VISITORS_ACTION_TAB: '# of unique unaffiliated visitors on action tab',
  CONVERSION_RATE_ACTION_TAB: 'conversion rate on action tab',
  NUMBER_OF_SIGNUPS_FAQ_TAB: '# of signups on faq tab',
  NUMBER_OF_UNIQUE_AFFILIATED_VISITORS_FAQ_TAB: '# of unique affiliated visitors on faq tab',
  NUMBER_OF_UNIQUE_UNAFFILIATED_VISITORS_FAQ_TAB: '# of unique affiliated visitors on faq tab',
  CONVERSION_RATE_FAQ_TAB: 'conversion rate on faq tab',
};
