const names = require('../keen/QueryNames');

module.exports = [
  names.NUMBER_OF_SIGNUPS,
  names.NUMBER_OF_UNIQUE_UNAFFILIATED_VISITORS,
  names.UNAFFILIATED_CONVERSION_RATE_OVERALL,
  names.NUMBER_OF_SIGNUPS_SCHOLARSHIP_TAB,
  names.NUMBER_OF_UNIQUE_UNAFFILIATED_VISITORS_SCHOLARSHIP_TAB,
  names.CONVERSION_RATE_SCHOLARSHIP_TAB,
  names.NUMBER_OF_SIGNUPS_COMMUNITY_TAB,
  names.NUMBER_OF_UNIQUE_UNAFFILIATED_VISITORS_COMMUNITY_TAB,
  names.CONVERSION_RATE_COMMUNITY_TAB,
  names.NUMBER_OF_SIGNUPS_ACTION_TAB,
  names.NUMBER_OF_UNIQUE_UNAFFILIATED_VISITORS_ACTION_TAB,
  names.CONVERSION_RATE_ACTION_TAB,
  names.NUMBER_OF_SIGNUPS_FAQ_TAB,
  names.NUMBER_OF_UNIQUE_UNAFFILIATED_VISITORS_FAQ_TAB,
  names.CONVERSION_RATE_FAQ_TAB,
];
